sudo: required
services:
  - docker
language: node_js
# IF NOT EXISTS is mariadb-10+ only - https://mariadb.com/kb/en/mariadb/comment-syntax/
before_install:
  - docker --version
node_js:
  - '0.12'
  - '4.6'
  - '6.7'


script:
  - docker run -d --name mysql -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -e MYSQL_DATABASE=test -p 3306:3306 mysql:5.7
  - docker run --link mysql:db -e CHECK_PORT=3306 -e CHECK_HOST=db giorgos/takis
  - "npm test"

#matrix:
#    include:
#        - addons:
#             mariadb: 5.5
#          node_js: '4.4'
#        - addons:
#             mariadb: 10.1
#          node_js: '4.4'
#        - addons:
#             mariadb: 5.5
#          node_js: '5.11'
#        - addons:
#             mariadb: 10.1
#          node_js: '5.11'
